[package]
name = "hexgen_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit="0.28.7"
glium="0.33.0"
tracing = "0.1"
