[package]
name = "hexgen_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russimp = {version = "2.0.6"}
tracing = "0.1"
glium="0.33.0"